version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql
    env_file: ./library_back/.env
    ports:
      - 5432:5432
  library_back:
    restart: "always"
    build: ./library_back
    env_file: ./library_back/.env
    command: bash -c "/library_back/entrypoint.sh"
    ports:
      - 8000:8000
    depends_on:
      - "db"